### ISSUE TITLE
issue with start parameter

### ISSUE THREAD

**Issue by SpEcHiDe** [Vontus/UrbanDictionaryBot#16]
https://core.telegram.org/bots#deep-linking

= is not a valid character according to the bot api documentation

**Comment by SpEcHiDe** [comment]
https://github.com/Vontus/UrbanDictionaryBot/blob/develop/src/formatter.ts#L36

I think 🤔 somewhere around this lines needs to have a change.

https://t.me/UrbanDictionaryBot?start=BoEwlgLgnghkA===

https://t.me/UrbanDictionaryBot?start=BoEwlgLgnghkA


both links seem to work even without trailing =.
I am not sure if it is a coincidence.

**Comment by Vontus** [comment]
Trailing = are padding for base64 encoding: [wikipedia](https://en.wikipedia.org/wiki/Base64)

**Comment by SpEcHiDe** [comment]
Hi, 

but it only works if we use https://github.com/DrKLO/Telegram/ OR https://github.com/telegramdesktop/tdesktop/

it is not working if we use https://t.me/tgx_log/330
